/**
 * Maps Google Font family names (as stored in config.json) to
 * the CSS custom properties generated by next/font/google.
 *
 * Usage:  style={{ fontFamily: resolveFontFamily(config.fonts.heading) }}
 */
const FONT_MAP: Record<string, string> = {
  'Barlow Condensed': 'var(--font-barlow-condensed)',
  'Bebas Neue': 'var(--font-bebas-neue)',
  'Cormorant Garamond': 'var(--font-cormorant-garamond)',
  'DM Sans': 'var(--font-dm-sans)',
  'DM Mono': 'var(--font-dm-mono)',
  'Geist': 'var(--font-geist)',
  'Inter': 'var(--font-inter)',
  'JetBrains Mono': 'var(--font-jetbrains-mono)',
  'Lora': 'var(--font-lora)',
  'Nunito': 'var(--font-nunito)',
  'Outfit': 'var(--font-outfit)',
  'Playfair Display': 'var(--font-playfair-display)',
  'Plus Jakarta Sans': 'var(--font-plus-jakarta-sans)',
  'Space Grotesk': 'var(--font-space-grotesk)',
  'Syne': 'var(--font-syne)',
  'Fraunces': 'var(--font-fraunces)',
  'Fragment Mono': 'var(--font-fragment-mono)',
  'Instrument Sans': 'var(--font-instrument-sans)',
  'Space Mono': 'var(--font-space-mono)',
  'Libre Baskerville': 'var(--font-libre-baskerville)',
  'Jost': 'var(--font-jost)',
}

export function resolveFontFamily(name: string): string {
  return FONT_MAP[name] ?? name
}

/**
 * Returns a TemplateConfig-compatible fonts object with CSS variable values.
 * Call this on the raw config before passing to components.
 */
export function resolveConfigFonts<T extends { fonts: { heading: string; body: string } }>(config: T): T {
  return {
    ...config,
    fonts: {
      heading: resolveFontFamily(config.fonts.heading),
      body: resolveFontFamily(config.fonts.body),
    },
  }
}
